FROM ubuntu:22.04

ENV HOME=/home

WORKDIR /home/dotfiles

COPY . /home/dotfiles

RUN apt-get update && apt-get install -y sudo

RUN test -f /home/dotfiles/ubuntu_based/install.sh && chmod +x /home/dotfiles/ubuntu_based/install.sh

CMD ["/bin/bash"]
