# INFO: wallpapers: http://wallhaven.cc/
splash = false

wallpaper {
    monitor = DP-2
    path = /home/marlliton/dotfiles/backgrounds/.config/backgrounds/reze.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/marlliton/dotfiles/backgrounds/.config/backgrounds/reze.jpg
    fit_mode = cover
}
